version: '3'
services:
  web:
    build: .
    command: >
      bash -c "
      npm install pm2 -g
      && npm run clean
      && npm run build
      && npm run test
      && pm2-runtime --node-args=\"--require dotenv/config\" start ./build/main.js -i max"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '8000:8000'
